import { encodeIdentifier } from "../utils/encodeIdentifier";

export class RuntimeProvider {
  
  /**
   * Generates the full Runtime Preamble (Standard Lib + Helpers)
   */
  public static getRuntimeShim(): string {
    return `
/**
 * 🦥 l-lang Runtime Preamble
 * Auto-generated by l-lang compiler
 */
"use strict";

// ==========================================================
// 1. External Dependencies
// ==========================================================

const _fs = require("fs");
const _util = require("util");
let _readline = null;
try { _readline = require("readline-sync"); } catch (e) { /* optional */ }

// ==========================================================
// 2. Core Operators (Mapped to l-lang encoded identifiers)
// ==========================================================
const ${encodeIdentifier('set!')} = (arr, i, val) => { arr[i] = val; return val; };
const ${encodeIdentifier('==')} = (a, b) => _ll_deep_eq(a, b);
const ${encodeIdentifier('!=')} = (a, b) => !_ll_deep_eq(a, b);
const ${encodeIdentifier('≠')}  = (a, b) => !_ll_deep_eq(a, b);

// Variadic Math
const ${encodeIdentifier('+')} = (...args) => args.reduce((a, b) => a + b);
const ${encodeIdentifier('-')} = (...args) => args.reduce((a, b) => a - b);
const ${encodeIdentifier('*')} = (...args) => args.reduce((a, b) => a * b);
const ${encodeIdentifier('/')} = (...args) => args.reduce((a, b) => a / b);

// Logical
const ${encodeIdentifier('||')} = (...args) => args.reduce((a, b) => a || b);
const ${encodeIdentifier('&&')} = (...args) => args.reduce((a, b) => a && b);

// Comparison
const ${encodeIdentifier('<')}  = (a, b) => a < b;
const ${encodeIdentifier('>')}  = (a, b) => a > b;
const ${encodeIdentifier('<=')} = (a, b) => a <= b;
const ${encodeIdentifier('>=')} = (a, b) => a >= b;

// List/Vector Ops
const head = (a) => (Array.isArray(a) && a.length > 0) ? a[0] : a;
const tail = (a) => (Array.isArray(a) && a.length > 0) ? a.slice(1) : a;
const empty = (a) => a === undefined || (Array.isArray(a) && a.length === 0);
const elem = (a, i) => a[i];
const cons = (...args) => args.reduce((acc, curr) => Array.isArray(curr) ? [...acc, ...curr] : [...acc, curr], []);

// ==========================================================
// 3. The 'std' Namespace
// ==========================================================
const std = {
  console: {
    log: console.log,
    error: console.error,
    print: (...args) => process.stdout.write(args.join("")),
    println: (...args) => process.stdout.write(args.join("") + "\\n"),
    read: (q) => _readline ? _readline.question(q || ">> ") : (() => { throw new Error("readline-sync not installed") })(),
  },
  math: Math,
  json: JSON,
  string: String,
  float: Number,
  int: (n) => parseInt(n),
  io: {
    "read-text": (path) => _fs.readFileSync(path, "utf-8"),
    "write-text": (path, data) => _fs.writeFileSync(path, data, "utf-8"),
  }
};
std.console.readln = std.console.read;

// ==========================================================
// 4. Runtime Helpers (Pattern Matching & Type Checking)
// ==========================================================

// Deep Equality Check
function _ll_deep_eq(a, b) {
  if (a === b) return true;
  if (a === null || b === null || typeof a !== 'object' || typeof b !== 'object') return false;
  
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (!_ll_deep_eq(a[i], b[i])) return false;
    return true;
  }
  
  const keysA = Object.keys(a);
  const keysB = Object.keys(b);
  if (keysA.length !== keysB.length) return false;
  for (const k of keysA) if (!keysB.includes(k) || !_ll_deep_eq(a[k], b[k])) return false;
  return true;
}

// Format Object (equivalent to util.format)
function __ll_format_object(obj) {
  return _util.formatWithOptions({ depth: null, colors: false }, obj || "");
}

// Pattern Matching - Lists
function _ll_match_list(val, patterns) {
  if (!Array.isArray(val)) return false;
  if (val.length !== patterns.length) return false;

  for (let i = 0; i < patterns.length; i++) {
    const pattern = patterns[i];
    const value = val[i];

    if (pattern === null || pattern === undefined) continue; // Wildcard

    // Handle Type Pattern: { type: 'string' }
    // Note: The transformer generates these objects for typed patterns
    if (typeof pattern === 'object' && pattern.type && pattern.__is_type_check) {
       if (!_ll_is_type(value, pattern.type)) return false;
    }
    // Handle Recursive List Pattern
    else if (Array.isArray(pattern)) {
       if (!_ll_match_list(value, pattern)) return false;
    }
    // Handle Object Pattern (Deep match)
    else if (typeof pattern === 'object') {
       // Deep equality for objects in list patterns? Or recursive struct match?
       // For now, let's assume recursive struct match
       if (!_ll_match_struct(value, pattern)) return false;
    }
    // Constant
    else {
       if (value !== pattern) return false;
    }
  }
  return true;
}

// Pattern Matching - Structs/Maps
function _ll_match_struct(val, patterns) {
  if (typeof val !== 'object' || val === null) return false;

  for (const key in patterns) {
    if (!(key in val)) return false; // Key existence check

    const pattern = patterns[key];
    const value = val[key];

    if (pattern === null || pattern === undefined) continue;

    if (typeof pattern === 'object' && pattern.type && pattern.__is_type_check) {
       if (!_ll_is_type(value, pattern.type)) return false;
    } 
    else if (Array.isArray(pattern)) {
       if (!_ll_match_list(value, pattern)) return false;
    }
    else if (typeof pattern === 'object') {
       if (!_ll_match_struct(value, pattern)) return false;
    } 
    else {
       if (value !== pattern) return false;
    }
  }
  return true;
}

// Type Checking
function _ll_is_type(val, type) {
  switch (type) {
    case 'number': return typeof val === 'number';
    case 'string': return typeof val === 'string';
    case 'boolean': return typeof val === 'boolean';
    case 'function': return typeof val === 'function';
    case 'array': return Array.isArray(val);
    case 'object': return typeof val === 'object' && val !== null && !Array.isArray(val);
    case 'null': return val === null;
    case 'undefined': return val === undefined;
    case 'any': return true;
    default:
      try {
        // Check for named classes (globals)
        return val instanceof eval(type); 
      } catch { return false; }
  }
}

// Call helper (for compatibility if needed, though pure JS calls are preferred)
const call = (f, args) => f(...args);

// ==========================================================
// End Preamble
// ==========================================================
`;
  }
}