
/**
 * 🦥 l-lang Runtime Preamble
 * Auto-generated by l-lang 0.0.1 compiler
 */
"use strict";
const _util = require("util");
let __ll_type_metadata = {};
let _readline = null;
try { _readline = require("readline-sync"); } catch (e) { /* optional */ }
function __ll_deep_eq(a, b) {
  if (a === b) return true;
  if (a === null || b === null || typeof a !== 'object' || typeof b !== 'object') return false;
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (!__ll_deep_eq(a[i], b[i])) return false;
    return true;
  }
  const keysA = Object.keys(a);
  const keysB = Object.keys(b);
  if (keysA.length !== keysB.length) return false;
  for (const k of keysA) if (!keysB.includes(k) || !__ll_deep_eq(a[k], b[k])) return false;
  return true;
}
function __ll_format_object(obj) { return _util.formatWithOptions({ depth: null, colors: false }, obj !== undefined && obj !== null ? obj : ""); }
const __ll_op_registry = {
  operators: {},
  register: function(symbol, params, fn) {
    if (!this.operators[symbol]) this.operators[symbol] = [];
    this.operators[symbol].push({ params, fn });
  },
  lookup: function(symbol, args) {
    const list = this.operators[symbol];
    if (!list) return null;
    for (const entry of list) {
      if (entry.params.length !== args.length) continue;
      let match = true;
      for (let i = 0; i < args.length; i++) {
        const val = args[i];
        const expectedType = entry.params[i];
        if (!__ll_is_type(val, expectedType)) {
          match = false;
          break;
        }
      }
      if (match) return entry.fn;
    }
    return null;
  }
};
function __ll_match_list(val, patterns) {
  if (!Array.isArray(val)) return false;
  if (val.length !== patterns.length) return false;
  for (let i = 0; i < patterns.length; i++) {
    const pattern = patterns[i];
    const value = val[i];
    if (pattern === null || pattern === undefined) continue; // Wildcard
    // Handle Type Pattern: { type: 'string' }
    // Note: The transformer generates these objects for typed patterns
    if (typeof pattern === 'object' && pattern.type && pattern.__is_type_check) {
       if (!__ll_is_type(value, pattern.type)) return false;
    }
    // Handle Recursive List Pattern
    else if (Array.isArray(pattern)) {
       if (!__ll_match_list(value, pattern)) return false;
    }
    // Handle Object Pattern (Deep match)
    else if (typeof pattern === 'object') {
       // Deep equality for objects in list patterns? Or recursive struct match?
       // For now, let's assume recursive struct match
       if (!__ll_match_struct(value, pattern)) return false;
    }
    // Constant
    else {
       if (value !== pattern) return false;
    }
  }
  return true;
}
function __ll_match_struct(val, patterns) {
  if (typeof val !== 'object' || val === null) return false;

  for (const key in patterns) {
    if (!(key in val)) return false; // Key existence check

    const pattern = patterns[key];
    const value = val[key];

    if (pattern === null || pattern === undefined) continue;

    if (typeof pattern === 'object' && pattern.type && pattern.__is_type_check) {
       if (!__ll_is_type(value, pattern.type)) return false;
    } 
    else if (Array.isArray(pattern)) {
       if (!__ll_match_list(value, pattern)) return false;
    }
    else if (typeof pattern === 'object') {
       if (!__ll_match_struct(value, pattern)) return false;
    } 
    else {
       if (value !== pattern) return false;
    }
  }
  return true;
}
function __ll_is_type(val, type) {
  const t = type.toLowerCase();
  switch (t) {
    case 'number': return typeof val === 'number';
    case 'int': return typeof val === 'number';
    case 'float': return typeof val === 'number';
    case 'string': return typeof val === 'string';
    case 'boolean': return typeof val === 'boolean';
    case 'bool': return typeof val === 'boolean';
    case 'function': return typeof val === 'function';
    case 'array': return Array.isArray(val);
    case 'object': return typeof val === 'object' && val !== null && !Array.isArray(val);
    case 'null': return val === null;
    case 'undefined': return val === undefined;
    case 'any': return true;
    default:
      if (val === null || val === undefined) return false;
      // Check constructor name (handles classes/structs even in IIFE)
      let current = val;
      while (current) {
        if (current.constructor && current.constructor.name === type) return true;
        // Also check l-lang specific type metadata if available
        if (current.__ll_type === type) return true;
        current = Object.getPrototypeOf(current);
        if (current === Object.prototype || !current) break;
      }
      return false;
  }
}
const list = (...args) => [...args];
const _3c  = (a, b) => a < b;
const _2b = (...args) => {
      if (args.length === 0) return 0;
      let res = args[0];
      for (let i = 1; i < args.length; i++) {
        const next = args[i];
        const overload = __ll_op_registry.lookup('+', [res, next]);
        if (overload) {
          res = overload(res, next);
        } else if (res && typeof res['_2b_1'] === 'function') {
          res = res['_2b_1'](next);
        } else {
          res = res + next;
        }
      }
      return res;
    };
const type = (typeNameOrObj) => {
  // If it's a string, look up the type metadata
  if (typeof typeNameOrObj === 'string') {
    return __ll_type_metadata[typeNameOrObj] || { name: typeNameOrObj, kind: 'unknown', properties: [], methods: [], generics: [] };
  }
  // If it's an object (instance), try to get its type
  if (typeof typeNameOrObj === 'object' && typeNameOrObj !== null) {
    const typeName = typeNameOrObj.constructor?.name || 'Object';
    return __ll_type_metadata[typeName] || { name: typeName, kind: 'object', properties: Object.keys(typeNameOrObj), methods: [], generics: [] };
  }
  // If it's a function (class), get its type
  if (typeof typeNameOrObj === 'function') {
    const typeName = typeNameOrObj.name;
    return __ll_type_metadata[typeName] || { name: typeName, kind: 'class', properties: [], methods: [], generics: [] };
  }
  return { kind: 'unknown', properties: [], methods: [], generics: [] };
};
__ll_type_metadata = {
  "print": {
    "name": "print",
    "kind": "function",
    "paramsList": [
      {
        "name": "msg",
        "type": "String"
      },
      {
        "name": "args",
        "type": "Any"
      }
    ],
    "returns": "Void",
    "nullable": false
  }
};

"use strict";
(function () {
  const __ll_inlined_zip_1 = (list, other) => {
    const result = [];
    const len = _3c(list.length, other.length) ? list.length : other.length;
    {
      let i = 0;
      for (; _3c(i, len); i = _2b(i, 1)) {
        result.push([list[i], other[i]]);
      }
    }
    return result;
  };
  const __ll_inlined_range_1 = (start, end, step) => {
    const result = [];
    {
      let i = start;
      for (; _3c(i, end); i = _2b(i, step)) {
        result.push(i);
      }
    }
    return result;
  };
  {
    ;
    function print(msg, ...args) {
      {
        let arg;
        for (arg of __ll_inlined_zip_1(args, __ll_inlined_range_1(0, args.length, 1))) {
          (__ll_tmp_match_id_1 => {
            let value, index;
            return Array.isArray(__ll_tmp_match_id_1) && __ll_tmp_match_id_1.length === 2 && (value = __ll_tmp_match_id_1[0], true) && (index = __ll_tmp_match_id_1[1], true) ? msg = msg.replace(_2b("{", index, "}"), value.toString()) : undefined;
          })(arg);
        }
      }
      return console.log(msg);
    }
    ;
  }
})();


//# sourceMappingURL=io.lisp.map;
