import path from "path";
import { SourceNode } from "source-map";

import * as ast from "../../../frontend/ast";

import { BaseAstVisitor } from "../../../BaseAstVisitor";
import { Context, LogLevel, VERSION } from "../../../Context";

import { RuntimeProvider } from "../../../runtime";

import { ScopeType, SymbolEntry } from "../../../analysis/SymbolTable";

import { 
  createSourceNode, 
  joinArray, 
  formatVariable, uniqueIdentifier, encodeIdentifier } from "../../../utils";

import { ClassBuilder } from "../ClassBuilder";

/**
 * Helper to extract variable names declared within a pattern match
 */
function findIdentifiersToDefine(node: ast.MatchNode): string[] {
  const predefinedVariables: string[] = [];
  const walkPattern = (p: ast.PatternNode): boolean => {
    switch (p._type) {
      case "identifier-pattern":
        const id = p.id.id;
        // Skip enum references (e.g., HttpMethod:GET) and runtime references
        if (!id.includes(":") && !RuntimeProvider.isRuntimeReference(id)) {
          predefinedVariables.push(encodeIdentifier(id));
        }
        return true;
      case "map-pattern":
        return (p as ast.MapPatternNode).pairs.every(x => walkPattern(x.pattern));
      case "list-pattern":
      case "vector-pattern":
        return (p as ast.ListPatternNode).elements.every(x => walkPattern(x));
      default:
        return true;
    }
  };
  node.cases.every(x => walkPattern(x.pattern));
  return Array.from(new Set(predefinedVariables));
}

export class JSTransformerAstVisitor extends BaseAstVisitor {
  private scope: ScopeType[] = [ScopeType.program];
  
  public functions: string[] = [];
  public classes: string[] = [];
  public variables: string[] = [];

  private enumKeys: Record<string, string> = {};
  private identifiersCache: Record<string, string> = {};
  private inlineStandardSymbols: string[] = [];
  // Symbols that were inlined from imported modules
  private inlinedSymbols: Record<string, string> = {};
  // Definitions (SourceNode or string parts) keyed by unique name
  private inlinedDefinitions: Record<string, (SourceNode | string)[]> = {};
  // Source file for the AST root currently being compiled
  private rootSource?: string;

  constructor(context: Context) {
    super(context);
  }

  // =========================================================================
  // Scope Helpers
  // =========================================================================

  private pushScope(nextScope: ScopeType) {
    this.scope.unshift(nextScope);
  }

  private popScope() {
    return this.scope.shift();
  }

  private currentScope(): ScopeType {
    return this.scope.at(0)!;
  }

  private inScope(...scopes: ScopeType[]) {
    return scopes.includes(this.currentScope());
  }

  /**
   * Determines if the current location requires an Expression (value) 
   * or accepts a Statement (void/action).
   * 
   * Expression contexts: variable assignments, and nested expressions.
   * Statement contexts: function bodies, if bodies at statement level, etc.
   */
  private isExpressionContext(): boolean {
    // Treat these parent scopes as expression contexts so nested
    // constructs (like `if` inside a `match` arm or `when` value)
    // emit expression-style code (ternaries / comma-exprs) instead
    // of statement-style `if { ... }` blocks.
    return this.scope.some(
      (s) => s === ScopeType.variable || s === ScopeType.match
    );
  }

  private runInScope<T>(scope: ScopeType, action: () => T): T {
    this.pushScope(scope);
    try {
      return action();
    } finally {
      this.popScope();
    }
  }

  // =========================================================================
  // Core
  // =========================================================================

  public compile(root: ast.ASTNode) {
    // Remember the root source so we can detect imports vs local symbols
    this.rootSource = root && root._location && root._location.source ? root._location.source : undefined;
    const rootSourceNode = this.visit(root);
    
    const header = [
      `/**`,
      ` * 🦥 l-lang Module ${this.context.mainModule}\n`,
      ` * Generated by l-lang v${VERSION}\n`,
      ` * Compiled at ${new Date().toISOString()}\n`,
      ` */\n`,
      `"use strict";\n`
    ];

    const standardLibrary = createSourceNode(root, RuntimeProvider.getRuntimeShimForSymbols(this.inlineStandardSymbols));
    const sourceName = root && root._location && root._location.source ? root._location.source : 'bundle.lisp';
    const sourceMapUrl = `\n\n//# sourceMappingURL=${path.basename(sourceName, '.lisp')}.js.map`;

    // Prepend any inlined definitions collected during traversal
    // console.log('inlinedDefinitions keys:', Object.keys(this.inlinedDefinitions));
    const defs = Object.values(this.inlinedDefinitions).flat();
    const defsWithSeparators = defs.length > 0 ? joinArray(defs, ';\n') : [];
    const wrappedBody = createSourceNode(root, '(function() {', '\n', ...defsWithSeparators, defs.length > 0 ? ';\n' : '', rootSourceNode, '\n', '})()');

    return createSourceNode(root,
      standardLibrary,
      ...header,
      wrappedBody,
      sourceMapUrl
    ).toStringWithSourceMap();
  }

  visitProgram(node: ast.ProgramNode) {
    // Top level program is a list of statements, joined by semicolons
    // Prefix with an empty statement to avoid accidental string-call when
    // the first statement is an expression starting with `(`.
    return createSourceNode(node, 
      ";\n",
      ...joinArray(node.program.map(n => this.visit(n)), ';\n')
    );
  }

  // =========================================================================
  // Classes
  // =========================================================================

  visitClass(node: ast.ClassNode) {
    this.classes.push(node.name.name);

    return this.runInScope(ScopeType.class, () => {
      const classBuilder = new ClassBuilder(node, this.context, this);
      return classBuilder.build();
    });
  }

  visitStruct(node: ast.StructNode) {
    // TODO: For JS we're treating structs as classes
    return this.visitClass(node as unknown as ast.ClassNode);
  }

  visitEnum(node: ast.EnumNode) {
    const enumName = node.name.name;
    const enumKeys = node.body.map((keyNode, keyIndex) => {
      const key = `${enumName}:${ast.keyName(keyNode.key)}`;
      const value = keyNode.value !== null ? this.visit(keyNode.value) : keyIndex.toString();
      this.enumKeys[key] = value;
      return createSourceNode(keyNode, `const `, encodeIdentifier(key), ` = `, value, `;`);
    });
    return createSourceNode(node, `/* enum ${enumName} definitions */`, ...enumKeys);
  }

  visitInterface(node: ast.InterfaceNode) {
    return this.runInScope(ScopeType.interface, () => {
      const name = this.visit(node.name);
      return createSourceNode(node, `/* interface ${name} (erased) */`);
    });
  }

  // =========================================================================
  // Functions & Variables
  // =========================================================================


  visitFunction(node: ast.FunctionNode) {
    const nextScope = this.inScope(ScopeType.class) 
      ? ScopeType.method 
      : ScopeType.function;

    return this.runInScope(nextScope, () => {
      const name = node.name && this.visit(node.name);
      if (name) {
          this.functions.push(name.toString());
      }

      const params = node.params.map((x) => this.visit(x));
      
      // Function Body Processing
      const bodyNodes = node.body.map((x, index) => {
        const visited = this.visit(x);
        
        // Implicit Return Logic
        if (index === node.body.length - 1) {
            
            // 1. Convert to string to check what we actually generated
            const visitedCode = visited.toString().trim();

            // 2. Check strict exclusions
            // - If it's already a return statement (Explicit return)
            // - If it starts with 'if', 'while', 'try', 'for' (Statements that can't be returned)
            // - If it's a variable declaration (const/let)
            
            const isAlreadyReturn = visitedCode.startsWith("return");
            const isControlStatement = visitedCode.startsWith("if") || 
                                       visitedCode.startsWith("while") ||
                                       visitedCode.startsWith("try") ||
                                       visitedCode.startsWith("for");
            const isVariable = x._type === 'variable';

            if (!isAlreadyReturn && !isControlStatement && !isVariable) {
                return createSourceNode(x, "return ", visited);
            }
        }
        
        return visited;
      });

      // ... rest of the existing logic (joining body, wrapping in function/method/arrow) ...
      let body: (SourceNode | string)[];

      if (bodyNodes.length === 0) {
        body = [];
      } else {
        body = joinArray(bodyNodes, ";");
      }

      // ... (keep the existing function signature generation logic) ...
      const parentScope = this.scope[1]; 
      
      if (this.currentScope() === ScopeType.method) {
        return createSourceNode(node,
            node.async ? "async " : "",
            name, "(", ...joinArray(params, ","), ") {",
            ...body,
            "}"
        );
      } else if (parentScope === ScopeType.program) {
        return createSourceNode(node,
            node.async ? "async " : "",
            "function ", name, "(", ...joinArray(params, ","), ") {",
            ...body,
            "}"
        );
      } else {
        const kw = node.async ? "async " : "";
        const arrow = [kw, "(", ...joinArray(params, ","), ") => {", ...body, "}"];
        
        if (name) {
            this.functions.push(name.toString());
            return createSourceNode(node, "const ", name, " = ", ...arrow);
        } else {
            return createSourceNode(node, ...arrow);
        }
      }
    });
  }

  visitVariable(node: ast.VariableNode) {
    this.pushScope(ScopeType.variable);
    const name = this.visit(node.name);
    const value = node.value ? this.visit(node.value) : undefined;
    this.popScope();

    this.variables.push(name.toString());

    return createSourceNode(node,
      formatVariable(
        this.currentScope(),
        node,
        node.mutable,
        name,
        value,
        this.context
      ));
  }

  visitParameter(node: ast.ParameterNode) {
    return this.visit(node.name);
  }

  // =========================================================================
  // Control Flow
  // =========================================================================

  visitIf(node: ast.IfNode) {
    return this.runInScope(ScopeType.if, () => {
      const condition = this.visit(node.condition!);
      const thenExpr = this.visit(node.then!);
      const elseExpr = node.else ? this.visit(node.else) : undefined;

      // If we are in an expression context (assignment, args), use Ternary
      if (this.isExpressionContext()) {
         return createSourceNode(node, 
            "(", condition, ") ? (", thenExpr, ") : (", elseExpr || "undefined", ")"
         );
      }

      // Statement context
      const elseBlock = elseExpr ? [" else { ", elseExpr, " }"] : [];
      return createSourceNode(node, 
        "if (", condition, ") { ", thenExpr, " }", ...elseBlock
      );
    });
  }

  visitWhen(node: ast.WhenNode) {
    return this.runInScope(ScopeType.when, () => {
      const condition = this.visit(node.condition!);
      const whenExprs = node.then!.map((x) => this.visit(x));
      const body = joinArray(whenExprs, ";");

      // Always use expression form - `when` is inherently an expression construct
      // (condition) ? (expr1, expr2, ...) : undefined
      return createSourceNode(node, 
          "(", condition, ") ? (", ...joinArray(whenExprs, ","), ") : undefined"
      );
    });
  }

  visitCond(node: ast.CondNode) {
    const cases = node.cases.map(condCase => this.visit(condCase));

    if(this.isExpressionContext()) {
      return createSourceNode(node, ...cases, `undefined /* we shouldn't get here */;`)
    }

    return createSourceNode(node, `switch (true) {`, ...cases, `}`);
  }

  visitCondCase(node: ast.CondCaseNode) {
    const cond = this.visit(node.condition);
    const then = this.visit(node.body);

    if(this.isExpressionContext()) {
      return createSourceNode(node, `(`, cond, `) ? `, then, ':');
    }

    return createSourceNode(node, `case (`, cond, `): {`, then, `}; break;`);
  }

  visitWhile(node: ast.WhileNode) {
    const condition = this.visit(node.condition);
    const body = this.visit(node.then);
    return createSourceNode(node, `while (`, condition, `) {`, body, `}`);
  }

  visitFor(node: ast.ForNode) {
    const init = this.visit(node.initial);
    const cond = this.visit(node.condition);
    const step = this.visit(node.step);
    const then = this.visit(node.then);
    const elseFor = node.else !== null ? this.visit(node.else) : ``;
    return createSourceNode(node, `{`, init, `; for ( /* empty */ ; `, cond, `; `, step, `) {`, then, `}; `, elseFor, `};`);
  }

  visitForEach(node: ast.ForEachNode) {
    const variable = this.visit(node.variable);
    const collection = this.visit(node.collection);
    const then = this.visit(node.then);
    const elseFor = node.else !== null ? this.visit(node.else) : ``;
    return createSourceNode(node, `{ let `, variable, `; for (`, variable, ` of `, collection, `) {`, then, `};`, elseFor, `}`);
  }

  visitTryCatch(node: ast.TryCatchNode) {
    const tryBlock = [ `try {`, this.visit(node.try), `}` ];
    const catchVar = uniqueIdentifier("tmp_catch_id"); 
    
    const catchBlocks = node.catch?.filter(x => !!x.filter)?.map(x => {
      const catchFilterVar = this.visit(x.filter.name);
      const catchFilterType = this.visit(x.filter.type);
      const catchBody = this.visit(x.body);
      
      // We need to declare the filtered var: const err = catchVar;
      return [
        `if (`, catchVar, ` instanceof `, catchFilterType, `) {`,
        `const `, catchFilterVar, ` = `, catchVar, `;`, 
        catchBody, 
        `}`
      ];
    });

    const defaultCatchNode = node.catch?.find(x => !x.filter);
    const defaultCatchBlock = defaultCatchNode 
      ? this.visit(defaultCatchNode.body) 
      : [`throw `, catchVar, `;`];

    const joinedCatchBody = catchBlocks && catchBlocks.length > 0
        ? [...joinArray(catchBlocks, ' else '), ' else { ', defaultCatchBlock, ' }']
        : defaultCatchBlock;

    const catchBlock = node.catch 
      ? [` catch (`, catchVar, `) {`, ...joinedCatchBody, `}`] 
      : [];
      
    const finallyBlock = node.finally 
      ? [` finally {`, this.visit(node.finally), `}`] 
      : [];

    return createSourceNode(node, ...tryBlock, ...catchBlock, ...finallyBlock);
  }

  // =========================================================================
  // Pattern Matching
  // =========================================================================

  visitMatch(node: ast.MatchNode) {
    return this.runInScope(ScopeType.match, () => {
      const matchVar = uniqueIdentifier("tmp_match_id");
      const matchVal = this.visit(node.expression);

      const matchCases = node.cases.map((x) => ({
        p: x.pattern,
        b: this.visit(x.body),
      }));

      const ifExprs = matchCases.map((x) => {
        const condition = this.generateCondition(x.p, matchVar);
        return createSourceNode(x.p, '(', condition, ')', '?', '(', x.b, ')');
      });

      const predefinedVariables = findIdentifiersToDefine(node);
      const predefinedVarsCode = predefinedVariables.length > 0
        ? `let ${predefinedVariables.join(',')};`
        : '';

      return createSourceNode(node, 
        `((`, matchVar, `) => { `, 
        predefinedVarsCode, 
        'return ', ...joinArray(ifExprs, ' : '), ' : undefined;', 
        '})(', matchVal, `)`
      );
    });
  }

  private generateCondition(pattern: ast.PatternNode, matchVar: string): SourceNode {
    switch (pattern._type) {
      case "any-pattern":
        return createSourceNode(pattern, `true`);
      case "identifier-pattern":
        // TODO: This is a quick patch. If id is in the seen enum definitions, the switch to constant-pattern
        if (pattern.id.id in this.enumKeys) {
          return createSourceNode(pattern, matchVar, ' === ', this.enumKeys[pattern.id.id]);
        }
        return createSourceNode(pattern, `(`, this.visit(pattern.id), '=', matchVar, `, true)`);
      case "constant-pattern":
        return createSourceNode(pattern, matchVar, ' === ', this.visit(pattern.constant));
      case "list-pattern":
      case "vector-pattern":
        return this.generateArrayPatternCondition(pattern as ast.ListPatternNode, matchVar);
      case "map-pattern":
        return this.generateMapPatternCondition(pattern as ast.MapPatternNode, matchVar);
      default:
        return createSourceNode(pattern, `false`);
    }
  }

  private generateArrayPatternCondition(pattern: ast.ListPatternNode | ast.VectorPatternNode, matchVar: string): SourceNode {
    const conditions: (string | SourceNode)[] = [];
    conditions.push(`Array.isArray(${matchVar})`);
    conditions.push(`${matchVar}.length === ${pattern.elements.length}`);
    pattern.elements.forEach((elem, idx) => {
      conditions.push(this.generateCondition(elem, `${matchVar}[${idx}]`));
    });
    return createSourceNode(pattern, ...joinArray(conditions, " && "));
  }

  private generateMapPatternCondition(pattern: ast.MapPatternNode, matchVar: string): SourceNode {
    const conditions: (string | SourceNode)[] = [];
    
    // 1. Basic object check
    conditions.push(`(typeof ${matchVar} === 'object' && ${matchVar} !== null)`);

    pattern.pairs.forEach((pair) => {
      let keyAccess: string | SourceNode;

      // 2. Determine Key Accessor
      // In L-lang maps: { :key val } -> Key is SimpleIdentifier "key"
      // We must treat it as a string literal property name, not a variable.
      if (pair.key._type === 'simple-identifier') {
          keyAccess = `"${(pair.key as ast.SimpleIdentifierNode).id}"`;
      } else if (pair.key._type === 'string') {
          keyAccess = `"${(pair.key as ast.StringNode).value}"`;
      } else {
          // Dynamic/Computed key (rare in patterns but possible)
          keyAccess = this.visit(pair.key);
      }
      
      const memberAccess = `${matchVar}[${keyAccess}]`;
      
      // 3. Generate condition for the value at that key
      conditions.push(this.generateCondition(pair.pattern, memberAccess));
    });

    return createSourceNode(pattern, ...joinArray(conditions, " && "));
  }

  // =========================================================================
  // Identifiers / Literals
  // =========================================================================

  visitIdentifier(node: ast.IdentifierNode) {
    // If we've already mapped this identifier to a string, use it
    if (this.identifiersCache[node.id]) return createSourceNode(node, this.identifiersCache[node.id]);

    // Resolve symbol in the symbol table (if available) to check whether
    // it originates from another module. If so, inline its definition
    // into this module under a unique name.
    try {
      const resolved = this.context?.symbolTable?.resolveSymbol?.(node as any);
      // debug: log resolution
      // console.log('visitIdentifier resolve', node.id, resolved ? (resolved.value && (resolved.value as any)._location && (resolved.value as any)._location.source) : undefined);
      if (resolved && resolved.value && resolved.value._location && this.rootSource && resolved.value._location.source !== this.rootSource) {
        const uniq = this.ensureSymbolInlined(resolved);
        this.identifiersCache[node.id] = uniq;
        return createSourceNode(node, uniq);
      }
    } catch (e) {
      // If anything goes wrong resolving, fall back to normal encoding
    }

    const id = encodeIdentifier(node.id);
    this.identifiersCache[node.id] = id;
    if (RuntimeProvider.isRuntimeReference(node.id)) {
      if (node._type === "composite-identifier") {
        let aggregate = node.parts[0];
        for (let i = 1; i < node.parts.length; ++i) {
          this.inlineStandardSymbols.push(aggregate);
          aggregate = `${aggregate}.${node.parts[i]}`;
        }
        this.inlineStandardSymbols.push(aggregate);
      } else {
        this.inlineStandardSymbols.push(node.id);
      }
    }
    return createSourceNode(node, id);
  }

  visitSimpleIdentifier(node: ast.SimpleIdentifierNode) { return this.visitIdentifier(node); }
  visitCompositeIdentifier(node: ast.CompositeIdentifierNode) { return this.visitIdentifier(node); }

  visitString(node: ast.StringNode) { return createSourceNode(node, `"`, node.value, `"`); }
  visitBoolean(node: ast.BooleanNode) { return createSourceNode(node, node.value.toString()); }
  visitIntegerNumber(node: ast.IntegerNumberNode) { return createSourceNode(node, node.value.toString()); }
  visitFloatNumber(node: ast.FloatNumberNode) { return createSourceNode(node, node.value.toString()); }

  visitFormattedString(node: ast.FormattedStringNode) {
    const value = node.value.map((x: ast.ASTNode) =>
      ast.isStringNode(x) ? x.value : this.visit(x)
    );
    return createSourceNode(node, "`", ...value, "`");
  }

  visitFormatExpression(node: ast.FormatExpressionNode) {
    return createSourceNode(node, "${__ll_format_object(", this.visit(node.expression), ")}");
  }

  // =========================================================================
  // Lists (The Core Logic)
  // =========================================================================

  visitList(node: ast.ListNode) {
    const nodes = Array.isArray(node.nodes) ? node.nodes : [node.nodes];
    if (nodes.length === 0) return createSourceNode(node, "null");

    const [head, ...rest] = nodes;
    const isHeadIdentifier = head._type === "simple-identifier" || head._type === "composite-identifier";

    if (isHeadIdentifier) {
        const headId = (head as any).id;

        if (head._type === 'simple-identifier' && headId === 'new' && rest.length > 0) {
            const className = this.visit(rest[0]);
            const args = rest.slice(1).map(x => this.visit(x));
            return createSourceNode(node, 'new ', className, '(', ...joinArray(args, ","), ')');
        }

        if (head._type === "simple-identifier" && headId === "return") {
            if (rest.length === 0) {
                return createSourceNode(node, "return");
            }
            const returnValue = this.runInScope(ScopeType.variable, () => this.visit(rest[0]));
            return createSourceNode(node, "return ", returnValue);
        }

        const callee = this.visit(head);
        const args = rest.map(x => this.visit(x));
        const calleeStr = callee.toString();

        // 1. Class Instantiation (Implicit 'new')
        // Now that visitClass registers early, this works for recursive calls too.
        if (this.classes.includes(calleeStr)) {
            return createSourceNode(node, 'new ', callee, '(', ...joinArray(args, ","), ')');
        }

        // 2. Resolve implicit Method Calls vs Property Access
        // We need to determine if we should add "()" or not.
        
        // Extract the effective name to check against known functions.
        // For "myFunc", it's "myFunc". For "dog.speak", it's "speak".
        let memberName = calleeStr;
        if (head._type === "composite-identifier") {
           const parts = calleeStr.split('.'); 
           memberName = parts[parts.length - 1];
        }

        const isKnownFunction = this.functions.includes(calleeStr) || this.functions.includes(memberName);

        // If it has arguments, it's definitely a call.
        // If it's a known function (even with 0 args), it's a call.
        if (args.length > 0 || isKnownFunction) {
           return createSourceNode(node, callee, '(', ...joinArray(args, ","), ')'); 
        }

        // 3. Fallback: 0 args and NOT a known function -> Property/Variable Access
        // This fixes the (this.name) -> this.name() bug.
        return createSourceNode(node, callee);
    }

    // Implicit Block / Sequence
    // ... rest of the existing function
    
    const statements = nodes.map(x => this.visit(x));

    if (false && this.isExpressionContext()) {
      // TODO: Remove this code it is doing nothing
      const last = statements[statements.length - 1];
      const body = statements.slice(0, -1).map(s => [s, ';']);
      
      return createSourceNode(node, 
        "(() => { ", ...body.flat(), " return ", last, "; })()"
      );
    } else {
      return createSourceNode(node, ...joinArray(statements, ";"));
    }
  }

  // =========================================================================
  // Misc
  // =========================================================================

  visitVector(node: ast.VectorNode) {
    return createSourceNode(node, '[', ...joinArray(node.values.map(x => this.visit(x)), ","), ']');
  }

  visitMatrix(node: ast.MatrixNode) {
    const rows = joinArray(node.rows.map(row => [`[`, ...joinArray(row.map(x => this.visit(x)), ","), `]` ]), ",").flat()
    return createSourceNode(node, `[`, ...rows, `]`);
  }

  visitMap(node: ast.MapNode) {
    return createSourceNode(node, '{', ...joinArray(node.values.map(x => this.visit(x)), ","), '}');
  }

  visitKeyValue(node: ast.KeyValueNode) {
    return createSourceNode(node, this.visit(node.key), ': ', this.visit(node.value));
  }

  visitSimpleAssignment(node: ast.SimpleAssignmentNode) {
    return createSourceNode(node, this.visit(node.assignable), ` = `, this.visit(node.value));
  }

  visitCompoundAssignment(node: ast.CompoundAssignmentNode) {
    const assignable = this.visit(node.assignable);
    const value = this.visit(node.value);
    return createSourceNode(node, assignable, ` = `, value, `/* Compound assignment '${node.operator}' */`);
  }

  visitIndexer(node: ast.IndexerNode) {
    const id = this.visit(node.id);
    const indices = node.indices.flatMap(x => [ '[', ...joinArray(x.map(y => this.visit(y)), "]["), ']' ]);
    return createSourceNode(node, id, ...indices);
  }

  visitComment(node: ast.CommentNode) { return createSourceNode(node, `// ${node.comment}\n`); }
  
  // Handling serialization of quotes for macros/AST access at runtime
  visitQuote(node: ast.QuoteNode) {
    const serialized = JSON.stringify(node, (key, val) => 
      ["_location", "_parent"].includes(key) ? undefined : val
    );
    return createSourceNode(node, serialized);
  }

  // Clone a node (structural clone) so we can safely modify names
  private cloneNode<T extends ast.ASTNode>(n: T): T {
    const cache = new Set<any>();
    return JSON.parse(JSON.stringify(n, (key, value) => {
      if (typeof value === 'object' && value !== null) {
        if (cache.has(value)) {
          // Circular reference found, discard key
          return;
        }
        // Store value in our collection
        cache.add(value);
      }
      return value;
    })) as T;
  }

  // Ensure an external symbol is inlined into the current module. Returns
  // the unique identifier name that refers to the inlined symbol.
  private ensureSymbolInlined(symbol: SymbolEntry): string {
    const src = (symbol.value && (symbol.value as any)._location && (symbol.value as any)._location.source) || "";
    const symName = (symbol.name as any).id ?? (symbol.name as any).name ?? String(Math.random());
    const key = `${src}::${symName}`;

    if (this.inlinedSymbols[key]) return this.inlinedSymbols[key];

    try {
      const uniq = uniqueIdentifier("inlined_" + encodeIdentifier(symName));
      this.inlinedSymbols[key] = uniq;

      // Build a top-level definition for the symbol depending on its type
      let defParts: (SourceNode | string)[] = [];

      if (symbol.nodeType === "function") {
        const fn = this.cloneNode(symbol.value as ast.FunctionNode) as ast.FunctionNode;
        // replace name
        fn.name = fn.name ? { ...fn.name, id: uniq } as any : { _type: "simple-identifier", id: uniq } as any;
        // Visiting the cloned function will inline any nested references as needed
        defParts = [ this.visit(fn) ];
      } else if (symbol.nodeType === "class") {
        const cls = this.cloneNode(symbol.value as ast.ClassNode) as ast.ClassNode;
        cls.name = cls.name ? { ...cls.name, name: uniq } as any : { _type: "identifier", name: uniq } as any;
        defParts = [ this.visit(cls) ];
      } else if (symbol.nodeType === "variable") {
        const v = this.cloneNode(symbol.value as ast.VariableNode) as ast.VariableNode;
        // create const uniq = <value>
        const valueNode = v.value ? this.visit(v.value) : "undefined";
        defParts = [ createSourceNode(v, "const ", uniq, " = ", valueNode, ";") ];
      } else {
        // fallback: try to visit the value node and assign to uniq
        const val = (symbol.value as any) ? this.visit(symbol.value as any) : "undefined";
        defParts = [ createSourceNode(symbol.value as any, "const ", uniq, " = ", val, ";") ];
      }

      this.inlinedDefinitions[uniq] = defParts;
      // console.log('inlinedDefinitions added', uniq);
      return uniq;
    } catch (ex) {
      console.error('ensureSymbolInlined error for', symName, ex);
      // Fallback: return a safe encoded name (no inlining)
      const fallback = encodeIdentifier(symName);
      return fallback;
    }
  }
}